In [2]:
import numpy as np

# Numpy Data Types and Attributes

In [3]:
# Numpy main data type is ndarray
a1 = np.array([1, 2, 3])

In [9]:
a1
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3], 
               [4, 5, 6]])

a3 = np.array([[[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]] ,
             [[10, 11, 12],
             [13, 14, 15],
             [16, 17, 18]]])

In [12]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [15]:
print(a3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [17]:
np.shape(a3)

(2, 3, 3)

In [19]:
a3.shape

(2, 3, 3)

In [22]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [23]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [24]:
a1.size, a2.size, a3.size

(3, 6, 18)

### Create Dataframe from numpy array

In [26]:
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

# Creat np arrays

In [28]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [29]:
sample_array.dtype

dtype('int32')

In [32]:
ones = np.ones((2, 3, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [34]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [38]:
random_array = np.random.randint(0, 10, size = (2, 3, 4))
random_array

array([[[3, 1, 7, 1],
        [2, 2, 1, 0],
        [3, 1, 6, 5]],

       [[6, 2, 7, 0],
        [7, 0, 4, 0],
        [9, 9, 2, 9]]])

In [39]:
random_array.size

24

In [41]:
random_array_2 = np.random.random((2, 3))
random_array_2

array([[0.84608184, 0.30891788, 0.7275438 ],
       [0.05002181, 0.7669001 , 0.33131125]])

In [43]:
random_array_3 = np.random.rand(2, 3)
random_array_3

array([[0.39585338, 0.1590396 , 0.65419546],
       [0.93000734, 0.96708362, 0.1009258 ]])

### Pseudo random number

In [5]:
# np.random.seed() --> make the array not change after rerun
np.random.seed(42)
random_array_4 = np.random.randint(0, 10, size = (2, 3, 4))
random_array_4

array([[[6, 3, 7, 4],
        [6, 9, 2, 6],
        [7, 4, 3, 7]],

       [[7, 2, 5, 4],
        [1, 7, 5, 1],
        [4, 0, 9, 5]]])

# 4. Manipulating & comparing array

In [7]:
a1 

array([1, 2, 3])

In [10]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [11]:
a1 + ones

array([2., 3., 4.])

In [12]:
a1 * ones

array([1., 2., 3.])

In [13]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [15]:
a1.shape, a2.shape

((3,), (2, 3))

In [16]:
a1 / ones

array([1., 2., 3.])

In [17]:
a1 / a2

array([[1.  , 1.  , 1.  ],
       [0.25, 0.4 , 0.5 ]])

In [18]:
# Floor division (round down)
a1 // a2

array([[1, 1, 1],
       [0, 0, 0]])

In [21]:
a2 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [22]:
np.square(a2)

array([[ 1,  4,  9],
       [16, 25, 36]])

## Aggregation
Perform the same operation on the number of things

In [24]:
sum(a1)

6

#### Python method (`sum()`) vs numpy method (`np.sum()`)

In [28]:
massive_array = np.random.random(100000)
massive_array[:10]

array([0.51427225, 0.98318435, 0.69745456, 0.76085209, 0.91675229,
       0.70403108, 0.83887703, 0.19756798, 0.76195023, 0.97090758])

In [29]:
%timeit sum(massive_array) # python sum()
%timeit np.sum(massive_array) # np.sum()

9.22 ms ± 671 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
50.2 µs ± 275 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [31]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
np.mean(a2)

3.5

In [33]:
np.std(a2)

1.707825127659933

In [35]:
# var = std ** 2
np.var(a2)

2.9166666666666665

## Reshape and transpose

In [44]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
a2.shape

(2, 3)

In [41]:
a3.shape

(2, 3, 3)

In [42]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [40]:
a2.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [46]:
a2_reshape = a2.reshape(2,3,1)

In [47]:
a2_reshape * a3

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 21,  24,  27]],

       [[ 40,  44,  48],
        [ 65,  70,  75],
        [ 96, 102, 108]]])

#### Transpose

In [49]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [50]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [51]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

## Dot Product

In [54]:
np.random.seed(42)
mat1 = np.random.randint(0, 9, size = (5, 3))
mat2 = np.random.randint(0, 9, size = (5, 3))

In [55]:
mat1, mat2

(array([[6, 3, 7],
        [4, 6, 2],
        [6, 7, 4],
        [3, 7, 7],
        [2, 5, 4]]),
 array([[1, 7, 5],
        [1, 4, 0],
        [5, 8, 0],
        [2, 6, 3],
        [8, 2, 4]]))

In [57]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [59]:
# Element-wise multiple - Hadamard product
mat1 * mat2

array([[ 6, 21, 35],
       [ 4, 24,  0],
       [30, 56,  0],
       [ 6, 42, 21],
       [16, 10, 16]])

In [62]:
# Dot product
mat2 = mat2.T
np.dot(mat1, mat2)

array([[62, 18, 54, 51, 82],
       [56, 28, 68, 50, 52],
       [75, 34, 86, 66, 78],
       [87, 31, 71, 69, 66],
       [57, 22, 50, 46, 42]])

In [64]:
# Dot product can be applied to multiple two dataframe like the example of nut-butter-sales

In [66]:
np.random.seed(0)
# number of jars sold
sale_amount = np.random.randint(20, size = (5,3))
sale_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [69]:
# Create weekly sale dataframe
import pandas as pd
weekly_sales = pd.DataFrame(sale_amount, 
                            index = ["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns = ["Amondl", "Peaneat", "Star"])
weekly_sales

Amondl  Peaneat  Star
Mon        12       15     0
Tues        3        3     7
Wed         9       19    18
Thurs       4        6    12
Fri         1        6     7

In [70]:
# Creat a price array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [73]:
# Creat butter prices dataframe
prices = pd.DataFrame(prices.reshape(1, 3), 
                      index = ["Prices"],
                      columns = ["Amondl", "Peaneat", "Star"])
prices

Amondl  Peaneat  Star
Prices      10        8    12

In [77]:
weekly_sales.shape, prices.shape

((5, 3), (1, 3))

In [79]:
daily_sales = np.dot(prices, weekly_sales.T)
daily_sales

array([[240, 138, 458, 232, 142]])

In [82]:
weekly_sales["Total sale"] = daily_sales.T
weekly_sales

Amondl  Peaneat  Star  Total sale
Mon        12       15     0         240
Tues        3        3     7         138
Wed         9       19    18         458
Thurs       4        6    12         232
Fri         1        6     7         142

# Comparision Operator

In [84]:
a1, a2

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [85]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [93]:
bool_array = a1 > a2
bool_array
bool_array.dtype

dtype('bool')

In [94]:
type(bool_array)

numpy.ndarray

In [96]:
a2 == a2

array([[ True,  True,  True],
       [ True,  True,  True]])

# Sorting array

In [114]:
random_array_5 = np.random.randint(10, size = (3, 5))
random_array_5

array([[8, 1, 3, 3, 3],
       [7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2]])

In [115]:
np.sort(random_array_5)

array([[1, 3, 3, 3, 8],
       [0, 1, 7, 9, 9],
       [0, 2, 3, 4, 7]])

In [116]:
random_array_5

array([[8, 1, 3, 3, 3],
       [7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2]])

In [117]:
# argsort - sort array and not change the position of array's elements
np.argsort(random_array_5)

array([[1, 2, 3, 4, 0],
       [1, 2, 0, 3, 4],
       [0, 4, 3, 1, 2]], dtype=int64)

In [118]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
np.argsort(a2)

array([[0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [110]:
np.argmin(a2)

0

In [111]:
np.argmin(random_array_5)

5

In [119]:
np.argmax(random_array_5, axis = 1)

array([0, 3, 2], dtype=int64)

In [120]:
np.argmax(random_array_5, axis = 0)

array([0, 2, 2, 1, 1], dtype=int64)

# Turn images into numpy array

<img src="numpy-images/panda.png" />

In [130]:
from matplotlib.image import imread

panda = imread("numpy-images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [134]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [135]:
panda[:100]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.06666667, 0.12156863, 0.07058824],
        [0.06666667, 0.12156863, 0.07058824],
        [0.06666667, 0