In [1]:
import numpy as np

# Numpy Data Types and Attributes

In [3]:
# Numpy main data type is ndarray
a1 = np.array([1, 2, 3])

In [9]:
a1
type(a1)

numpy.ndarray

In [11]:
a2 = np.array([[1, 2, 3], 
               [4, 5, 6]])

a3 = np.array([[[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]] ,
             [[10, 11, 12],
             [13, 14, 15],
             [16, 17, 18]]])

In [12]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [15]:
print(a3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [17]:
np.shape(a3)

(2, 3, 3)

In [19]:
a3.shape

(2, 3, 3)

In [22]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [23]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [24]:
a1.size, a2.size, a3.size

(3, 6, 18)

### Create Dataframe from numpy array

In [26]:
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

# Creat np arrays

In [28]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [29]:
sample_array.dtype

dtype('int32')

In [32]:
ones = np.ones((2, 3, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [34]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [38]:
random_array = np.random.randint(0, 10, size = (2, 3, 4))
random_array

array([[[3, 1, 7, 1],
        [2, 2, 1, 0],
        [3, 1, 6, 5]],

       [[6, 2, 7, 0],
        [7, 0, 4, 0],
        [9, 9, 2, 9]]])

In [39]:
random_array.size

24

In [41]:
random_array_2 = np.random.random((2, 3))
random_array_2

array([[0.84608184, 0.30891788, 0.7275438 ],
       [0.05002181, 0.7669001 , 0.33131125]])

In [43]:
random_array_3 = np.random.rand(2, 3)
random_array_3

array([[0.39585338, 0.1590396 , 0.65419546],
       [0.93000734, 0.96708362, 0.1009258 ]])

### Pseudo random number

In [ ]:
# np.random.seed() --> make the array not change after rerun
np